export const SET_GRAPH = "SET_GRAPH";
export const SET_DISTANCE_TYPE = "SET_DISTANCE_TYPE";
export const SET_START = "SET_START";
export const SET_FINISH = "SET_FINISH";
export const SET_ACTIVE_ITEM = "SET_ACTIVE_ITEM";
export const SET_SHOW_LINK_DOTS = "SET_SHOW_LINK_DOTS";
export const SET_SHOW_NODE_TITLES = "SET_SHOW_NODE_TITLES";
